# This is a basic workflow to help you get started with Actions

name: Deploys Site to Azure over SSH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - uses: actions/checkout@main

      # Copying files and artifacts via SSH
      #- name: Copying files to server
      #  uses: garygrossgarten/github-action-ssh@v0.5.0
      #  with:
      #    host: ${{ secrets.REMOTE_HOST }}
      #    username: ${{ secrets.REMOTE_USER }}
      #    key: ${{ secrets.SSH_KEY }}
      #    passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
      #    rm: true
      #    source: "/"
      #    target: "${{ secrets.REMOTE_DIR }}"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          #key: ${{ secrets.SSH_KEY }}
          #passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: whoami
