name: Deploys Site to Azure over SSH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        
      - name: ls -a via ssh
        uses: fifsky/ssh-action@v0.0.4
        with:
          command: |
            cd /tmp
            ls -a
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
      
      #- name: Deploy to Staging server 1
      #  uses: easingthemes/ssh-deploy@v2.1.5
      #  env:
      #    SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      #    ARGS: "-rltgoDzvO"
      #    SOURCE: "site/"
      #    REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #    REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #    TARGET: ${{ secrets.REMOTE_DIR }}
      #    PORT: ${{ secrets.SSH_PORT }}
